format = """
[](#61afef)\
$os\
[](fg:#61afef bg:#e5c07b)\
$username\
[](fg:#e5c07b bg:#be5046)\
$cmd_duration\
[](fg:#be5046 bg:#89ca78)\
$directory\
[](fg:#89ca78 bg:#d55fde)\
$git_branch\
$git_status\
[](fg:#d55fde bg:#abb2bf)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#abb2bf bg:#2bbac5)\
$docker_context\
[ ](fg:#2bbac5)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# represents the current operating system
[os.symbols]
Debian = " "
Windows = " "
[os]
style = "bg:#61afef fg:#2c2c2c"
disabled = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#e5c07b fg:#2c2c2c"
style_root = "bg:#e5c07b fg:#ef596f"
format = '[ $user ]($style)'
disabled = false

[cmd_duration]
style = "bg:#be5046 fg:#ffffff"
format = '[ 󰥔 $duration ]($style)'

[directory]
style = "bg:#89ca78 fg:#2c2c2c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#d55fde fg:#2c2c2c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d55fde fg:#2c2c2c"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = "bg:#abb2bf fg:#2c2c2c"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#2bbac5"
format = '[ $symbol$context ]($style) $path'
