format = """
[](bright-white)\
$os\
[](fg:bright-white bg:blue)\
$username\
[](fg:blue bg:red)\
$cmd_duration\
[](fg:red bg:green)\
$directory\
[](fg:green bg:purple)\
$git_branch\
$git_status\
[](fg:purple bg:yellow)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:yellow bg:cyan)\
$docker_context\
[](fg:cyan bg:bright-white)\
$shell\
[ ](fg:bright-white)\
"""

# add_newline = false

[os.symbols]
Debian = " "
Ubuntu = " "
Windows = " "
Unknown = " "
[os]
style = "bg:bright-white fg:black"
disabled = false

[username]
show_always = true
style_user = "bg:blue fg:black"
style_root = "bg:blue fg:bright-red"
format = '[ $user ]($style)'
disabled = false

[cmd_duration]
style = "bg:red fg:black"
format = '[ 󰥔 $duration ]($style)'

[directory]
style = "bg:green fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:purple fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:purple fg:black"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[elixir]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = "bg:yellow fg:black"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:cyan"
format = '[ $symbol$context ]($style) $path'

[shell]
cmd_indicator = " "
bash_indicator = " "
fish_indicator = "󰈺 "
powershell_indicator = "󰨊 "  
zsh_indicator = "󰬡 "
nu_indicator = "󰬕 "
unknown_indicator = "? "
format = '[ $indicator]($style)'
style = "bg:bright-white fg:black"
disabled = false
